version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel_app
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    networks:
      - laravel_net
    depends_on:
      - db
    environment:
      APP_ENV=local
      DB_HOST=db
      DB_PORT=3306
      DB_DATABASE=login_season
      DB_USERNAME=laravel
      DB_PASSWORD=secret

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - vendor:/var/www/html/vendor
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: login_season
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel_net

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    tty: true
    networks:
      - laravel_net

volumes:
  vendor:
  node_modules:
  dbdata:

networks:
  laravel_net:
    driver: bridge
